class QuizQuestionAndAnswers {
  var questionsAndAnswers = [
    ['In what unit is the thickness of the ozone layer measured?', ['Dobson Unit', 'Pascal', 'atm', 'Mickey unit', 'Dobson Unit']],
    ['Who popularised the famous slogan, "Ecology is the permanent economy"? (hint: this person was one of the pioneers of the Chipko movement)', ['Sunderlal Bahuguna', 'Vandana Shiva', 'Chandi Prasad Bhatt', 'Sunita Narain', 'Sunderlal Bahuguna']],
    ["The Bombay Stock Exchange (BSE) launched a new Green Index - termed as India's first carbon-efficient live index in collaboration with IIM Ahmedabad. What is the name of the index?", ['EPI', 'Sustainability Index', 'Greenex', 'Greenday Index', 'Greenex']],
    ['To what important discovery in the field of environmental degradation do we attribute the chemists, Frank Rowland and Mario Molina?', ['Ozone Layer Depletion', 'El Nino and La Nina', 'Eutrophication', 'Biological Oxygen Demand', 'Ozone Layer Depletion']],
    ["What is the name of India's first all-electric vehicle, developed by Mahindra?", ['Rudra', 'Varuna', 'Reva', 'Elxsi', 'Reva']],
    ['What comic book series achieved the distinction of being the first to be printed entirely on recycled paper as early as the mid-1980s?', ['Archie Comics', 'Marvel Comics', 'Amar Chitra Katha', 'DC Comics', 'Archie Comics']],
    ["Which national park in Jammu Kashmir, whose name literally means 'ten villages', is a natural habitat for the critically-endangered Kashmir Stag?", ['Hemis National Park', 'Kazinag National Park', 'Dachigam National Park', 'Kishtwar National Park', 'Dachigam National Park']],
    ['The Bronx Zoo in New York once had a picture frame covered by a cloth, which was labelled "The most dangerous species in the world". If one were to remove the cloth, which species would one see?', ['Gorilla', 'Orangutan', 'Homo Sapiens', 'Rhinoceros', 'Homo Sapiens']],
    ['A phenomenon is named after this scientist who discovered it on Feb 28, 1927 and won a Nobel prize for it in 1930. Which scientist?', ['Wolfgang Pauli', 'CV Raman', 'Ernest Fermi', 'Paul Erdos', 'CV Raman']],
    ['What is the name given to a vehicle which uses two or more power sources to run?', ['Electric vehicle', 'Hybrid vehicle', 'Ion vehicle', 'Solar vehicle', 'Solar vehicle']],
    ['What is the name of the nodal agency that coordinates the energy conservation activities under the Environmental Conservation Act, India?', ['Bureau of Indian Standards', ', Bureau of Energy Conversation', 'Bureau of Energy Efficiency', 'Bureau of Energy and Resources', 'Bureau of Energy Efficiency']],
    ['Which farming method among the following is used in hilly areas to reduce soil erosion? It creates multiple small dams and slows down water flow to promote better water quality.', ['Contour farming', 'Multiple Cropping', 'Crop Rotation', 'Jhum Cultivation', 'Contour farming']],
    ['This Indian scientist and environmentalist was knighted by the British in 1941. He is also known as ‘The Father of Research Laboratories’. Who? (hint: an annual award by the CSIR is conferred in his name).', ['Shekhar C Mande', 'Girish Sahni', 'G. S. Sidhu', 'Shanti Swarup Bhatnagar', 'Shanti Swarup Bhatnagar']],
    ['Known as Danti in Hindi and Rajanyot in Gujarati, this plant is highly resistant and its oil is used for energy purposes after treatment with ethanol and caustic soda. Which plant?', ['Ashoka', 'Eucalyptus', 'Jatropha', 'Neem', 'Jatropha']],
    ['Which international standard for energy efficient consumer products was created in the early 1990s by the United States Environmental Protection Agency?', ['Energy Star', 'Blue Star', 'Protection Star', 'Protection Star', 'Energy Star']],
    ['This protocol was ratified by 196 countries across the globe and has been hailed as the most successful international protocol till date. What am I talking about?', ['Geneva Convention', 'Montreal Protocol', 'Nuclear Relations Agreement', 'BIS Convention', 'Montreal Protocol']],
    ['The Athabasca deposit in Canada is the world’s largest source for which natural resource?', ['Cobalt', 'oil tar', 'coal', 'biomass', 'oil tar']],
    ['Which World Heritage Site in India in India is home to two-thirds of the world’s one horned rhinoceros?', ['Ranthambore', 'Dachigam', 'Kaziranga', 'Jim Corbett', 'Kaziranga']],
    ['Which Indian politician started the organisation People for Animals in 1992, the largest organisation for animal welfare in India?', ['Maneka Gandhi', 'Atal Bihari Vajpayee', 'Narendra Modi', 'PV Narasimha Rao', 'Maneka Gandhi']],
    ['Which movement began in September 1983 when people led by Panduranga Hegde hugged the trees in the Kalase forest?', ['Chipko movement', 'Appiko movement', 'Bishnoi movement', 'Narmada Bachao Andolan', 'Appiko movement']],
    ['Which environmentalist shared the Nobel prize with Al Gore in 2007?', ['Kailash Satyarthi', 'Sunderlal Bahuguna', 'David Attenborough', 'RK Pachauri', 'RK Pachauri']],
    ['On this day in 1972, the Stockholm Conference was held in Sweden for the first time. What do we better know this day as?', ['Water Day', 'World Wildlife Day', 'World Environment Day', 'Earth Day', 'World Environment Day']],
    ['This natural formation was described by the CNN as one of the 7 natural wonders of the world. Which?', ['Mount Matterhorn', 'Great Barrier Reef', 'Niagara Falls', 'Machu Picchu', 'Great Barrier Reef']],
    ['Which of the following is added to compost to speed up the process and get faster results?', ['Bugs', 'Ants', 'Worms', 'Snakes', 'Worms']],
    ['Which landmark global conference was the first major step to recognise the atmosphere as a natural resource and reduce greenhouse gas emissions?', ['Vienna Convention', 'Montreal Protocol', 'Stockholm Conference', 'Rio Earth Summit', 'Rio Earth Summit']],
    ['Which of the following is the most potent greenhouse gas?', ['Methane', 'water vapour', 'sulphur hexafluoride', 'carbon dioxide', 'sulphur hexafluoride']],
    ['What resource does the plant with the biological name Crocus sativus provide?', ['Cumin seeds', 'Saffron', 'Opium', 'Turmeric', 'Saffron']],
    ['What is the name of the world’s largest glacier in eastern Antarctica?', ['Lambert Glacier', 'Meola Glacier', 'Mertz Glacier', 'David Glacier', 'Lambert Glacier']],
    ['Which environmentalist has won both a Nobel and an Oscar?', ['David Attenborough', 'George Monbiot', 'Al Gore', 'Leonardo DiCaprio', 'Al Gore']],
    ['Which Indian emperor passed a law in the 3rd century B.C which prevented the cutting of trees for personal use?', ['Ashoka', 'Chalukya', 'Rajaraja Chola', 'Maurya', 'Ashoka']],
    ['The three women – Jane Goodall, Dian Fossey, and Birute Galdikas are collectively known as what, for their extensive study and works towards the conservation of gorillas?', ['Trimates', 'Musketeers', 'Orangutans', 'Gorilla’s Angels', 'Trimates']],
    ['What is the name of Wikipedia’s annual photo contest with an aim towards the conservation of the environment?', ['Wiki Long Life', 'Wiki Photo World', 'Wiki Loves Earth', 'Wiki Conservation Contest', 'Wiki Loves Earth']],
    ['Which scientist is popularly known as the ‘Father of Acid Rain’? ', ['Joseph Black', ', David Brewster', 'Humphry Davy', 'Robert Angus Smith', 'Robert Angus Smith']],
    ['Which now-extinct avian species is mentioned in the story books Alice in Wonderland?', ['Great Auk', 'Dodo', 'Passenger Pigeon', 'Tasmanian Tiger', 'Dodo']],
    ['Which national park finds its image on the back of the 20-rupee notes in Indian currency?', ['Jim Corbett National Park', 'Kaziranga National Park', 'Balpakram National Park', 'Mount Harriet National Park', 'Mount Harriet National Park']],
    ['Which global independent NGO was started by former Soviet Union president in 1993 with its headquarters in Geneva?', ['Conservation International', 'Green Cross', 'MIT Press', 'World Resources Institute', 'Green Cross']],
    ['Which national park is also called Mowgli Land, for being the setting of the book of the same name?', ['Keoladeo National Park', 'Kaziranga National Park', 'Pench National Park', 'Periyar National Park', 'Pench National Park']],
    ['Which university in India holds the record for the maximum number of bird species found across its campus?', ['JNU', 'Jamia', 'IIT Bombay', 'Tezpur University', 'JNU']],
    ['When is the Wildlife Week celebrated?', ['1-7 Oct', '15-21 Oct', '1-7 June', '15-21 June', '1-7 Oct']],
    ['The Ramsar Convention refers to the conservation of which?', ['Deserts', 'Forests', 'Agriculture Lands', 'Wetlands', 'Wetlands']],
    ['The pyramid of energy of an ecosystem is always', ['Inverted', 'Upright', 'Both', 'None', 'Upright']],
    ['Where in India is the Salim Ali Bird Sanctuary located?', ['Puducherry', 'Anakkatti', 'Thattekad', 'Palakkad', 'Thattekad']],
    ['Which of the following is an example of nitrogen-fixing bacteria in the soil?', ['Rhizobium', 'Nostoc', 'Nitrobacter', 'Azotobacter', 'Azotobacter']],
    ['Which of the following is the centre for modern nuclear technology in India?', ['BARC', 'SARC', 'CRAS', 'CSIR', 'BARC']],
    ['The Desert Oak is a type of tree whose roots can go deep into the ground, sometimes 30 times the height of the tree above the ground. Where is this found?', ['Dubai', 'Rajasthan', 'Sahara', 'Russia', 'Rajasthan']],
    ['When is the World Oceans Day celebrated?', ['7 March', '7 September', '8 July', '8 June', '8 June']],
    ['Which airport in India is the first one to be completely solar-powered?', ['Bodhgaya', 'Indore', 'Puducherry', 'Chennai', 'Puducherry']],
    ['In India, all vehicles in use have to obtain this certificate to certify emission check. What is it called?', ['Pollution Under Control', 'Emission Under Control', 'Emission Under Check', 'Pollution Under Check', 'Pollution Under Control']]
  ];
}